config/routes.rb
Rails.application.routes.draw do
  resources :mechanics
  resources :countries
  resources :states
  resources :cities
  resources :repair_orders
  resources :manuals
  resources :technical_reports
  resources :cars
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'repair_orders#index'

  get '/chassis_numbers' => 'cars#get_chassis_numbers'
  get '/repair_order_numbers' => 'repair_orders#get_numbers'
  get '/get_car_by_chassis_number/:chassis_number' => 'cars#get_by_chassis_number'
  get '/get_car_by_client_identification/:identification' => 'cars#get_by_client_identification'
  get '/import_data_from_ayax/:chassis_number'=>'repair_orders#import_from_ayax'
  #get '/repair_orders/' => 'repair_orders#index'
  post '/get_repair_orders_by_chassis_number' => 'repair_orders#get_by_chassis_number'
  post '/get_repair_orders_by_order_number' => 'repair_orders#get_by_order_number'

  post '/clients/get_by_name' => 'clients#get_by_name'
  post '/cars/get_by_identification' => 'cars#get_by_identification'
end

app/models/technical_report.rb
class TechnicalReport < ApplicationRecord
  belongs_to :car
end

app/controllers/technical_reports_controller.rb
class TechnicalReportsController < ApplicationController
  before_action :set_technical_report, only: [:show, :edit, :update, :destroy]
  before_action :set_cars, only: [:new, :edit]

  # GET /technical_reports
  # GET /technical_reports.json
  def index
    @technical_reports = TechnicalReport.paginate(:page => params[:page], :per_page => 10).order('id DESC')
  end

  # GET /technical_reports/1
  # GET /technical_reports/1.json
  def show
  end

  # GET /technical_reports/new
  def new
    @technical_report = TechnicalReport.new
  end

  # GET /technical_reports/1/edit
  def edit
  end

  # POST /technical_reports
  # POST /technical_reports.json
  def create
    @technical_report = TechnicalReport.new(technical_report_params)

    respond_to do |format|
      if @technical_report.save
        format.html { redirect_to @technical_report, notice: 'Technical report was successfully created.' }
        format.json { render :show, status: :created, location: @technical_report }
      else
        format.html { render :new }
        format.json { render json: @technical_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_reports/1
  # PATCH/PUT /technical_reports/1.json
  def update
    respond_to do |format|
      if @technical_report.update(technical_report_params)
        format.html { redirect_to @technical_report, notice: 'Technical report was successfully updated.' }
        format.json { render :show, status: :ok, location: @technical_report }
      else
        format.html { render :edit }
        format.json { render json: @technical_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technical_reports/1
  # DELETE /technical_reports/1.json
  def destroy
    @technical_report.destroy
    respond_to do |format|
      format.html { redirect_to technical_reports_url, notice: 'Technical report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_report
      @technical_report = TechnicalReport.find(params[:id])
    end

    def set_cars
      @cars = Car.all.pluck(:name, :id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_report_params
      params.require(:technical_report).permit(:car_id, :picture)
    end
end

app/helpers/technical_reports_helper.rb
module TechnicalReportsHelper
end

app/views/technical_reports/_form.html.erb
<%= form_for(technical_report, html: { class: "form-horizontal", role: "form"}) do |f| %>
  <% if technical_report.errors.any? %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h2><%= pluralize(technical_report.errors.count, "error") %> prohibited this technical report from being saved:</h2>

    <ul>
      <% technical_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="col-lg-6">
    <div class="well bs-component">

      <div class="form-group">
        <%= f.label t(:car), class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.select :car_id, @cars, {}, { class: "form-control", required: true } %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :picture, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :picture, class:'form-control', required: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/technical_reports/edit.html.erb
<div class="alert alert-dismissable alert-warning">
  <%= t('under_development') %>
</div>
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), technical_reports_path, class: 'btn btn-primary btn-back' %>
  <%= link_to t('show'), @technical_report, class: 'btn btn-primary btn-back' %>
  <h1><%= t('editing_technical_report') %></h1>
  </div>
</div>

<%= render 'form', technical_report: @technical_report %>

app/views/technical_reports/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables"><%= t('technical_reports') %></h1>
  </div>

  <div class="row">
    <%= link_to t('new_technical_report'), new_technical_report_path, class:"btn btn-primary" %>
  </div>

  <div class="bs-component">
    <table class="table table-striped table-hover ">

      <thead>
        <tr>
          <th><%= t('activerecord.attributes.technical_report.car') %></th>
          <th><%= t('activerecord.attributes.technical_report.picture') %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @technical_reports.each do |technical_report| %>
          <tr>
            <td><a href="<%= car_path(technical_report.car) %>"><%= technical_report.car.name %></a></td>
            <td><a href="<%= technical_report.picture %>"><%= technical_report.picture %></a></td>
            <td><%= link_to t('show'), technical_report %></td>
            <td><%= link_to t('edit'), edit_technical_report_path(technical_report) %></td>
            <td><%= link_to t('destroy'), technical_report, method: :delete, data: { confirm: t('are_you_sure?') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @technical_reports, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/technical_reports/new.html.erb
<div class="alert alert-dismissable alert-warning">
  <%= t('under_development') %>
</div>
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), technical_reports_path, class: 'btn btn-primary btn-back new__back-button' %>
  <h1 class="new__title"><%= t('new_technical_report') %></h1>
  </div>
</div>

<%= render 'form', technical_report: @technical_report %>

app/views/technical_reports/show.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="alert alert-dismissable alert-warning">
  <%= t('under_development') %>
</div>
<h1><%= t('information_of') %> <%= t('technical_report') %></h1>

<div class="col-lg-4">
  <table class="table table-striped table-hover ">
    <tbody>
      <tr>
        <td>
          <strong><%= t('car') %></strong>
        </td>
        <td>
          <a href="<%= car_path(@technical_report.car) %>"><%= @technical_report.car.name %></a>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('picture') %></strong>
        </td>
        <td>
          <a href="<%= @technical_report.picture %>"><%= @technical_report.picture %></a>
        </td>
      </tr>
    </tbody>
  </table>

  <%= link_to t(:edit), edit_technical_report_path(@technical_report), class:"btn btn-primary" %>
  <%= link_to t(:back), technical_reports_path, class:"btn btn-primary" %>
</div>