config/routes.rb
Rails.application.routes.draw do
  resources :mechanics
  resources :countries
  resources :states
  resources :cities
  resources :repair_orders
  resources :manuals
  resources :technical_reports
  resources :cars
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'repair_orders#index'

  get '/chassis_numbers' => 'cars#get_chassis_numbers'
  get '/repair_order_numbers' => 'repair_orders#get_numbers'
  get '/get_car_by_chassis_number/:chassis_number' => 'cars#get_by_chassis_number'
  get '/get_car_by_client_identification/:identification' => 'cars#get_by_client_identification'
  get '/import_data_from_ayax/:chassis_number'=>'repair_orders#import_from_ayax'
  #get '/repair_orders/' => 'repair_orders#index'
  post '/get_repair_orders_by_chassis_number' => 'repair_orders#get_by_chassis_number'
  post '/get_repair_orders_by_order_number' => 'repair_orders#get_by_order_number'

  post '/clients/get_by_name' => 'clients#get_by_name'
  post '/cars/get_by_identification' => 'cars#get_by_identification'
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_one :manual
  has_many :technical_reports
  has_many :repair_orders

  alias_attribute :name,:model

  def client?
    self.client != nil
  end

  def self.get_by_chassis_number chassis_number
    @car = self.where("chassis_number = ?", "#{chassis_number}")
    @car.first
  end

  def self.get_by_identification identification
    self.where("chassis_number ilike ? or engine_number ilike ? or plate ilike ?",
     "%#{identification}%", "%#{identification}%", "%#{identification}%").order('updated_at DESC').limit(40)
  end

  def name
    "#{self.brand} #{self.model} (Chasis: #{self.chassis_number.upcase})" #, Cliente: #{self.client.name})
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_clients, only: [:new, :edit]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.paginate(:page => params[:page], :per_page => 10).order('id DESC')
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /get_car_by_chassis_number/1
  def get_by_chassis_number
    @car = Car.order('chassis_number DESC').where("chassis_number = ?", "#{params[:chassis_number]}").limit(10)
    render json: @car
  end

  # GET /get_car_by_client_identification/1
  def get_by_client_identification
    @client = Client.where("identification = ?", "#{params[:identification]}").first

    @car = 'not found'
    @car = @client.cars unless @client.nil?

    render json: @car
  end

  # GET /cars/get_by_identification
  def get_by_identification
    @cars = Car.get_by_identification params[:car_identification]
    render :layout => false
  end

  # GET /get_chassis_numbers/1
  def get_chassis_numbers
    @chassis_numbers = Car.order('updated_at DESC').where("chassis_number ilike ?", "%#{params[:term]}%").limit(10)
    render json: @chassis_numbers.map(&:chassis_number)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def set_clients
      @clients = Client.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:client_id, :brand, :model, :chassis_number, :engine_number, :plate, :kilometers, :sell_date, :car_identification)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_cars_table.erb
<table id="cars_table" class="table table-striped table-hover ">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.car.brand') %></th>
      <th><%= t('activerecord.attributes.car.model') %></th>
      <th><%= t('activerecord.attributes.car.chassis_number') %></th>
      <th><%= t('activerecord.attributes.car.client') %></th>
      <th><%= t('activerecord.attributes.car.engine_number') %></th>
      <th><%= t('activerecord.attributes.car.plate') %></th>
      <th><%= t('activerecord.attributes.car.sell_date') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.chassis_number %></td>
        <td>
        <% if car.client? %>
          <a href="<%= client_path(car.client) %>"><%= car.client.name %></a>
        <% end %>
        </td>
        <td><%= car.engine_number %></td>
        <td><%= car.plate %></td>

        <td><%= car.sell_date %></td>
        <td><%= link_to t('show'), car %></td>
        <td><%= link_to t('edit'), edit_car_path(car) %></td>
        <td><%= link_to t('destroy'), car, method: :delete, data: { confirm: t('are_you_sure?') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/_form.html.erb
<%= form_for(car, html: { class: "form-horizontal", role: "form"}) do |f| %>
  <% if car.errors.any? %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

    <ul>
    <% car.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

<div class="col-lg-6">
  <div class="well bs-component">

    <div class="form-group">
      <%= f.label t(:chassis_number), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :chassis_number, class:'form-control', required: true %>
      </div>
    </div>

    <% @options = [] %>
    <% @clients.each do |client| %>
      <% @option = [] %>
      <% @option << client.first_name.to_s + ' ' + client.last_name.to_s %>
      <% @option << client.id.to_s %>
      <% @options << @option %>
    <% end %>

    <div class="form-group">
      <%= f.label t(:client), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :client_id, @options, {}, { class:'form-control', required: true } %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:brand), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :brand, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:model), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :model, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:engine_number), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :engine_number, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:plate), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :plate, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:sell_date), class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.date_select :sell_date, {use_month_names: [t(:jan), t(:feb), t(:mar), t(:apr), t(:may), t(:jun), t(:jul), t(:aug), t(:sep), t(:oct), t(:nov), t(:dec)],start_year: 1970, end_year: Time.current.year, class:'form-control' } %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/cars/_repair_orders_table.erb
<table id="repair_orders_table" class="table table-striped table-hover ">

  <thead>
    <tr>
      <th><%= t('activerecord.attributes.repair_order.order_number') %></th>
      <th><%= t('activerecord.attributes.repair_order.client_id') %></th>
      <th><%= t('activerecord.attributes.repair_order.type') %></th>
      <th><%= t('activerecord.attributes.repair_order.description') %></th>
      <th><%= t('activerecord.attributes.repair_order.note') %></th>
      <th><%= t('activerecord.attributes.repair_order.kilometers') %></th>
      <th><%= t('activerecord.attributes.repair_order.in_ayax') %></th>
      <th><%= t('activerecord.attributes.repair_order.repair_date') %></th>
      <th><%= t('activerecord.attributes.repair_order.created_at') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% repair_orders.each do |repair_order| %>
      <tr>
        <td><%= repair_order.order_number %></td>
        <td>
        <% if repair_order.car? && repair_order.car.client? %>
          <a href="<%= client_path(repair_order.car.client) %>"><%= repair_order.car.client.name %></a>
        <% end %>
        </td>
        <td><%= !repair_order.order_type.nil? ? t(repair_order.order_type.downcase) : '' %></td>
        <td><%= repair_order.description %></td>
        <td><%= repair_order.note %></td>
        <td><%= repair_order.kilometers %></td>
        <td><%= repair_order.ayax ? t('yes') : t('no') %></td>
        <td><%= repair_order.repair_date %></td>
        <td><%= repair_order.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= link_to t('show'), repair_order_path(repair_order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/edit.html.erb
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), cars_path, class: 'btn btn-primary btn-back' %>
  <%= link_to t('show'), @car, class: 'btn btn-primary btn-back' %>
  <h1><%= t('editing_car') %></h1>
  </div>
</div>

<%= render 'form', car: @car %>

app/views/cars/get_by_identification.erb
<%= render 'cars_table', cars: @cars %>

app/views/cars/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="form-horizontal">
      <div class="col-lg-5 no-padding">
        <div class="well bs-component">
          <div class="form-group">
            <label class="col-lg-3 control-label" for="car_identification"><%= t('search_car') %></label>

            <div class="col-lg-9">
              <input class="form-control ui-autocomplete-input" type="text" id="car_identification" autofocus autocomplete="off" placeholder="<%= t('search_car_placeholder') %>">
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="page-header" style="margin: 0; float: right; padding-right: 10px;">
      <h1 id="tables"><%= t('cars') %></h1>
    </div>
  </div>

  <div class="row">
      <%= link_to t('new_car'), new_car_path, class:"btn btn-primary" %>
  </div>
</div>

<div class="col-lg-12">
  <div class="bs-component">
    <%= render 'cars_table', cars: @cars %>
    <div class='pagination'>
      <%= will_paginate @cars, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#car_identification').on('change input autocompleteselect',function(event, ui){
      getCars('/cars/get_by_identification','car_identification='+$(this).val());
    });
  });

  var current_timeout = undefined;

  function getCars(url,data)
  {
    clearTimeout(current_timeout);

    current_timeout = setTimeout(function(){
      if ($('#car_identification').val().length > 0)
      {
        $('.pagination').addClass('hidden');

        $.post(url,data,function(data){
          $('#cars_table').html(data);
        });
      } else {
        window.location.search = '?page=1';
      }
    }, 700);

  }
</script>

app/views/cars/new.html.erb
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), cars_path, class: 'btn btn-primary btn-back new__back-button' %>
  <h1 class="new__title"><%= t('new_car') %></h1>
  </div>
</div>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-4">

  <h2><%= t('information_of') %> <%= @car.name %></h2>
  <%= link_to t(:edit), edit_car_path(@car), class:"btn btn-primary" %>
  <%= link_to t(:back), cars_path, class:"btn btn-primary" %>

  <table class="table table-striped table-hover ">
    <tbody>
      <tr>
        <td>
          <strong><%= t('client') %></strong>
        </td>
        <td>
          <a href="<%= client_path(@car.client) %>"><%= @car.client.name %></a>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('brand') %></strong>
        </td>
        <td>
          <%= @car.brand %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('model') %></strong>
        </td>
        <td>
          <%= @car.model %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('chassis_number') %></strong>
        </td>
        <td>
          <%= @car.chassis_number %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('engine_number') %></strong>
        </td>
        <td>
          <%= @car.engine_number %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('plate') %></strong>
        </td>
        <td>
          <%= @car.plate %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t('sell_date') %></strong>
        </td>
        <td>
          <%= @car.sell_date %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<div class="col-lg-8">

  <h1><%= t('car_repair_orders') %></h1>

  <%= render 'repair_orders_table', repair_orders: @car.repair_orders.order('order_number DESC') %>
</div>