config/routes.rb
Rails.application.routes.draw do
  resources :mechanics
  resources :countries
  resources :states
  resources :cities
  resources :repair_orders
  resources :manuals
  resources :technical_reports
  resources :cars
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'repair_orders#index'

  get '/chassis_numbers' => 'cars#get_chassis_numbers'
  get '/repair_order_numbers' => 'repair_orders#get_numbers'
  get '/get_car_by_chassis_number/:chassis_number' => 'cars#get_by_chassis_number'
  get '/get_car_by_client_identification/:identification' => 'cars#get_by_client_identification'
  get '/import_data_from_ayax/:chassis_number'=>'repair_orders#import_from_ayax'
  #get '/repair_orders/' => 'repair_orders#index'
  post '/get_repair_orders_by_chassis_number' => 'repair_orders#get_by_chassis_number'
  post '/get_repair_orders_by_order_number' => 'repair_orders#get_by_order_number'

  post '/clients/get_by_name' => 'clients#get_by_name'
  post '/cars/get_by_identification' => 'cars#get_by_identification'
end

app/models/repair_order.rb
class RepairOrder < ApplicationRecord
  belongs_to :car
  belongs_to :mechanic

  def car?
    self.car != nil
  end

  def car_chassis_number
    car.try(:name)
  end

  def car_chassis_number=(name)
    self.car = Car.find_by(chassis_number: name) if name.present?
  end

  def ci_number
    self.car.try(:name)
  end

  def ci_number=(name)
    self.car.client.ci = Car.find_by(ci_number: name) if name.present?
  end

  def car_select
    "car_select"
  end

  def self.get_by_order_number order_number
    repair_order = self.where("order_number = ?", "#{order_number}")
    repair_order.first
  end

  def self.get_many_by_order_number order_number
    repair_orders = self.where("CAST(order_number AS TEXT) ilike ?", "%#{order_number}%").order('order_number DESC').limit(40)
    repair_orders = [] unless !repair_orders.nil?
    repair_orders
  end

  def self.get_by_chassis_number chassis_number
    car = Car.get_by_chassis_number chassis_number

    repair_orders = car.repair_orders unless car.nil?
    repair_orders = [] unless !repair_orders.nil?
    repair_orders
  end

  def self.get_by_identification identification
    client = Client.get_by_identification identification
    repair_orders = nil
    unless client.nil? then
      # if client.cars.empty? then
      #   repair_orders = []
      # else
        client.cars.each do |car|
          if repair_orders.nil? then
            repair_orders = car.repair_orders
          else
            repair_orders += car.repair_orders
          end
        end
      # end
    end

    repair_orders = repair_orders.nil? ? [] : repair_orders
    repair_orders
  end

end

app/controllers/repair_orders_controller.rb
class RepairOrdersController < ApplicationController
  before_action :set_repair_order, only: [:show, :edit, :update, :destroy]
  before_action :set_last_repair_order_id, only: [:new, :edit]
  before_action :set_mechanics, only: [:new, :edit]

#'MA3FC31S6FA744592'
  def send_to_ayax data
    cookie = get_ayax_cookie params[:repair_order][:car_chassis_number]

    #data = "tipo=4&kms=34725&tiporep=Motor&descrep=descripcion&nroord=8888&obs=observacion&fecing=16%2F01%2F2017&tecnico=tecnico&agregar=Agregar"
    #data_example = "tipo=4&kms=34725&tipomant=Mantenimiento+35000+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++&descrep=CAMBIO+DE+ACEITE+Y+FILTRO&nroord=7266&obs=&fecing=09%2F01%2F2017&tecnico=FERNANDO&agregar=Agregar"

    path = '/grabarHistorial.php'

    headers = {
      "Accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Encoding" => "zip, deflate",
      "Accept-Language" => "en-US,en;q=0.8",
      "Cache-Control" => "max-age=0",
      "Connection" => "keep-alive",
      "Content-Length" => data.length.to_s,
      "Content-Type" => "application/x-www-form-urlencoded",
      "Cookie" => cookie,
      "Host" => "www.dat-ayax.com",
      "Origin" => "http://www.dat-ayax.com",
      "Referer" => "http://www.dat-ayax.com/Historialvehiculo.php?flujo=valchassis",
      "Upgrade-Insecure-Requests" => "1",
      "User-Agent" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
    }

    http = Net::HTTP.new('www.dat-ayax.com')

    res = http.post(path, data, headers)

    res
  end

  def import_from_ayax
    cookie = get_ayax_cookie params[:chassis_number]

    # Get the xls file
    download = open("http://www.dat-ayax.com/armoArchExcel.php?pchassis=#{@chassis_number}",
      'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
      'Accept-Encoding' => 'gzip, deflate, sdch',
      'Accept-Language' => 'en-US,en;q=0.8',
      'Connection' => 'keep-alive',
      'Cookie' => cookie,
      'Host' => 'www.dat-ayax.com',
      'Referer' => 'http://www.dat-ayax.com/Historialvehiculo.php?flujo=valchassis',
      'Upgrade-Insecure-Requests' => '1',
      'User-Agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'
    )
    IO.copy_stream(download, 'downloads/data.xls')

    xls = Roo::Excel.new("downloads/data.xls", format: :xls)

    # Create a Client with xls info
    @client = nil
    unless xls.sheet('Propietarios').first_column.nil?
      xls.sheet('Propietarios').each_with_index do |row, index|
        unless index == 0
          identification = row[0].to_i.to_s
          first_name = row[1].to_s
          last_name =  row[2].to_s
          address =  row[3].to_s
          city_name =  row[4].to_s
          telephone =  row[5].to_i
          email = row[6].to_s

          city = City.get_by_name city_name
          if city.nil? && !city_name.empty? then
            city = City.create(name: city_name, state: State.find(1))
          end

          @client = Client.get_by_identification identification
          if @client.nil? then
            @client = Client.create(city_id: city.id, first_name: first_name,last_name: last_name,address: address, email:email,telephone: telephone,identification: identification)
          end
        end
      end
    else
      @client = Client.first
    end

    # Create a Car with xls info
    @car = nil
    xls.sheet('Datos Vehiculo').each_with_index do |row, index|
      unless index == 0
        chassis_number = row[0].to_s
        brand =  row[2].to_s
        model =  row[4].to_s
        plate =  row[5].to_i
        engine_number = row[6].to_s
        sell_date = !row[7].nil? ? Date::strptime(row[7].to_s, '%d/%m/%Y') : ''

        @car = Car.get_by_chassis_number chassis_number
        if @car.nil? then
          @car = Car.create(client_id: @client.id,brand: brand,model: model, chassis_number: chassis_number, engine_number: engine_number, plate: plate, sell_date: sell_date)
        end
      end
    end

    # Create Repair Orders with xls info
    @repair_order = nil
    unless xls.sheet('Historial').first_column.nil?
      xls.sheet('Historial').each_with_index do |row, index|
        unless index == 0
          type = row[1].to_s
          create_date = !row[2].nil? ? Date::strptime(row[2].to_s, '%d/%m/%Y') : ''
          kilometers =  row[3].to_s
          description = row[5].to_s
          order_number = row[6].to_s
          note =  row[7].to_s
          repair_date =  !row[8].nil? ? Date::strptime(row[8].to_s, '%d/%m/%Y') : ''
          compliance_date = !row[9].nil? ? Date::strptime(row[9].to_s, '%d/%m/%Y') : ''
          mechanic_name = row[10].to_s

          mechanic = Mechanic.get_by_name mechanic_name
          if mechanic.nil? && !mechanic_name.empty? then
            mechanic = Mechanic.create(first_name: mechanic_name, city: City.find(1))
          end

          type_association = Hash.new
          type_association['Reclamo de Garantia'] = 'Warranty'
          type_association['Campaña'] = 'Campaign'
          type_association['Reparacion'] = 'Repair'
          type_association['Mantenimiento'] = 'Service'

          unless order_number.empty?
            @repair_order = RepairOrder.get_by_order_number order_number.to_i
            if @repair_order.nil? then
              @repair_order = RepairOrder.create(car_id: @car.id,
                                                 mechanic_id: mechanic.id,
                                                 order_number: order_number,
                                                 description: description,
                                                 note: note,
                                                 ayax: true,
                                                 kilometers: kilometers,
                                                 repair_date: repair_date,
                                                 compliance_date: compliance_date,
                                                 created_at: create_date,
                                                 order_type: type_association[type])
            end
          end
        end
      end
    end

    render json: []
  end

  # GET /repair_orders
  # GET /repair_orders.json
  def index
    @repair_orders = RepairOrder.paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
    @chassis_number = params[:chassis_number] unless params[:chassis_number].nil?
    @repair_order_number = params[:repair_order_number] unless params[:repair_order_number].nil?
    #@chassis_numbers = Car.all.pluck(:chassis_number)
  end

  # GET /repair_orders/1
  # GET /repair_orders/1.json
  def show
  end

  # GET /repair_orders/new
  def new
    @repair_order = RepairOrder.new
  end

  # GET /repair_orders/1/edit
  def edit
  end

  # POST /repair_orders
  # POST /repair_orders.json
  def create
    @repair_order = RepairOrder.new(repair_order_params)

    respond_to do |format|
      if @repair_order.save
        prepare_data_and_send_to_ayax
        format.html { redirect_to repair_order_path(@repair_order), notice: 'Repair order was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order }
      else
        format.html { render :new }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_orders/1
  # PATCH/PUT /repair_orders/1.json
  def update
    respond_to do |format|
      if @repair_order.update(repair_order_params)
        #prepare_data_and_send_to_ayax
        format.html { redirect_to repair_order_path(@repair_order), notice: 'Repair order was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order }
      else
        format.html { render :edit }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def prepare_data_and_send_to_ayax
    if @repair_order.ayax

      type_association = Hash.new
      #type_association['Warranty'] = ''
      type_association['Campaign'] = '1'
      type_association['Repair'] = '2'
      type_association['Service'] = '4'

      if @repair_order.order_type == "Service"
        data = URI.encode_www_form("tipo" => type_association[@repair_order.order_type],
                                   "kms" => @repair_order.kilometers,
                                   "tipomant" => @repair_order.ayax_service_type,
                                   "descrep" => @repair_order.description,
                                   "nroord" => @repair_order.order_number,
                                   "obs" => @repair_order.note,
                                   "fecing" => @repair_order.repair_date.strftime("%d/%m/%Y"),
                                   "tecnico" => @repair_order.mechanic.first_name,
                                   "agregar" => "Agregar")
      elsif @repair_order.order_type == "Repair"
        data = URI.encode_www_form("tipo" => type_association[@repair_order.order_type],
                                   "kms" => @repair_order.kilometers,
                                   "tiporep" => @repair_order.ayax_repair_type,
                                   "descrep" => @repair_order.description,
                                   "nroord" => @repair_order.order_number,
                                   "obs" => @repair_order.note,
                                   "fecing" => @repair_order.repair_date.strftime("%d/%m/%Y"),
                                   "tecnico" => @repair_order.mechanic.first_name,
                                   "agregar" => "Agregar")
      elsif @repair_order.order_type == "Campaign"
        data = URI.encode_www_form("tipo" => type_association[@repair_order.order_type],

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper
  def campaign_path campaign
    repair_order_path campaign
  end
  def repair_path repair
    repair_order_path repair
  end
  def service_path service
    repair_order_path service
  end
  def warranty_path warranty
    repair_order_path warranty
  end
end

app/views/repair_orders/_repair_orders_table.erb
<table id="repair_orders_table" class="table table-striped table-hover ">

  <thead>
    <tr>
      <th><%= t('activerecord.attributes.repair_order.order_number') %></th>
      <th><%= t('activerecord.attributes.repair_order.car_id') %></th>
      <th><%= t('activerecord.attributes.repair_order.client_id') %></th>
      <th><%= t('activerecord.attributes.repair_order.type') %></th>
      <th><%= t('activerecord.attributes.repair_order.description') %></th>
      <th><%= t('activerecord.attributes.repair_order.note') %></th>
      <th><%= t('activerecord.attributes.repair_order.kilometers') %></th>
      <th><%= t('activerecord.attributes.repair_order.in_ayax') %></th>
      <th><%= t('activerecord.attributes.repair_order.repair_date') %></th>
      <th><%= t('activerecord.attributes.repair_order.created_at') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% repair_orders.each do |repair_order| %>
      <tr>
        <td><%= repair_order.order_number %></td>
        <td>
        <% if repair_order.car? %>
          <a href="<%= car_path(repair_order.car) %>"><%= repair_order.car.name %></a>
        <% end %>
        </td>
        <td>
        <% if repair_order.car? && repair_order.car.client? %>
          <a href="<%= client_path(repair_order.car.client) %>"><%= repair_order.car.client.name %></a>
        <% end %>
        </td>
        <td><%= !repair_order.order_type.nil? ? t(repair_order.order_type.downcase) : '' %></td>
        <td><%= repair_order.description %></td>
        <td><%= repair_order.note %></td>
        <td><%= repair_order.kilometers %></td>
        <td><%= repair_order.ayax ? t('yes') : t('no') %></td>
        <td><%= repair_order.repair_date %></td>
        <td><%= repair_order.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= link_to t('show'), repair_order_path(repair_order) %></td>
        <td><%= link_to t('edit'), edit_repair_order_path(repair_order) %></td>
        <td><%= link_to t('destroy'), repair_order_path(repair_order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/repair_orders/edit.html.erb
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), repair_orders_path, class: 'btn btn-primary btn-back' %>
  <%= link_to t('show'), repair_order_path(@repair_order), class: 'btn btn-primary btn-back' %>
  <h1><%= t('editing_repair_order') %></h1>
  </div>
</div>

<%= render 'form', repair_order: @repair_order %>

app/views/repair_orders/get_by_chassis_number.erb
<%= render 'repair_orders_table', repair_orders: @repair_orders %>

app/views/repair_orders/get_by_identification.erb
<%= render 'repair_orders_table', repair_orders: @repair_orders %>

app/views/repair_orders/get_by_order_number.erb
<%= render 'repair_orders_table', repair_orders: @repair_orders %>

app/views/repair_orders/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>
<div class="container-fluid">

  <div class="row">
    <div class="form-horizontal">
      <div class="col-lg-6 no-padding">
        <div class="well bs-component">
          <div class="form-group">
            <label class="col-lg-2 control-label repair-order__search-title" for="repair_order_Buscar auto"><%= t('search_order') %></label>
            <div class="col-lg-3 search-car-toggle repair-order__search-toggle">
              <div class="togglebutton">
                <label>
                  <%= t('by_order_number') %> &nbsp; &nbsp;<input id="toggle_button" onclick="changeSearchType(this);" type="checkbox" checked=""> <%= t('by_chassis_number') %>
                </label>
              </div>
            </div>
            <div class="col-lg-4 repair-order__search-input">
              <input class="form-control ui-autocomplete-input" data-autocomplete-source="/chassis_numbers" type="text" name="repair_order[car_chassis_number]" id="repair_order_car_chassis_number" autocomplete="off" autofocus value="<%= @chassis_number %>">
              <input class="form-control hidden ui-autocomplete-input" data-autocomplete-source="/repair_order_numbers" type="text" name="repair_order[repair_order_number]" id="repair_order_ci_number" autocomplete="off" value="<%= @repair_order_number %>">
            </div>
            <div class="col-lg-3 repair-order__search-import">
              <div class="btn-group btn-group-justified btn-group-raised">
                <a class="btn btn-primary" id="import_btn" onClick="importFromAyax()" disabled="true" title="<%= t('import_data_from_ayax') %>">
                  <%= t('import') %>
                  <span id="refresh_icon" class="glyphicon glyphicon-refresh" aria-hidden="true" style="display: none;"></span>
                  <span id="okay_icon" class="glyphicon glyphicon-ok" aria-hidden="true" style="display:none;"></span>
                  <span id="fail_icon" class="glyphicon glyphicon-remove" aria-hidden="true" style="display: none; color: #dc0f00;"></span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="page-header" style="margin: 0; float: right; padding-right: 10px;">
      <h1 id="tables"><%= t('repair_orders') %></h1>
    </div>
  </div>

  <div class="row">
    <%= link_to t('new_repair_order'), new_repair_order_path, class:"btn btn-primary" %>
  </div>
</div>

<div class="col-lg-12">
  <div id="repair_orders_table" class="bs-component">
    <%= render 'repair_orders_table', repair_orders: @repair_orders %>
    <%= will_paginate @repair_orders, renderer: BootstrapPagination::Rails %>
  </div>
</div>

<script type="text/javascript">
  $('#repair_order_car_chassis_number').autocomplete({ source: $('#repair_order_car_chassis_number').data('autocomplete-source')});
  $('#repair_order_ci_number').autocomplete({source: $('#repair_order_ci_number').data('autocomplete-source')});

  $(document).ready(function(){
  if ($('#repair_order_car_chassis_number').val())
    $('#repair_order_car_chassis_number').change();

  if ($('#repair_order_ci_number').val())
    $('#repair_order_ci_number').change();
  })

  $('#repair_order_car_chassis_number').on('change input autocompleteselect',function(event, ui){
    if ($(this).val().length == 17)
      getRepairOrders('/get_repair_orders_by_chassis_number/','chassis_number='+$(this).val(),true);
    else if (ui)
      getRepairOrders('/get_repair_orders_by_chassis_number/','chassis_number='+ui.item.value,true);
    else
    {
      $('#import_btn').attr('disabled',true);
      $('#refresh_icon').css('display','none');
      $('#okay_icon').css('display','none');
      $('#fail_icon').css('display','none');
    }

    if ($(this).val().length === 0) {
      window.location.search = '?page=1';
    }

  });

  $('#repair_order_ci_number').on('change input autocompleteselect',function(event, ui){
    if (ui)
      getRepairOrders('/get_repair_orders_by_order_number/','order_number='+ui.item.value,false);
    else if ($(this).val().length > 0)
      getRepairOrders('/get_repair_orders_by_order_number/','order_number='+$(this).val(),false);

    if ($(this).val().length === 0) {
      window.location.search = '?page=1';
    }
  });

  var current_timeout = undefined;

  function getRepairOrders(url,data,canImport)
  {
    clearTimeout(current_timeout);

    if (canImport)
      $('#import_btn').attr('disabled',false);

    current_timeout = setTimeout(function(){
      $.post(url,data,function(data){$('#repair_orders_table').html(data)});
    }, 700);
  }

  function changeSearchType(elem) {
    toggleSearchType(elem);
    $('#import_btn').attr('disabled',true);

    if ($(elem).prop('checked'))
    {
      chassis_number_el = $('#repair_order_car_chassis_number');
      //$('#import_btn').attr('disabled',false);
      if (chassis_number_el.val().length == 17)
        getRepairOrders('/get_repair_orders_by_chassis_number/','chassis_number='+chassis_number_el.val(),true);
    }
    else
    {
      ci_number_el = $('#repair_order_ci_number');
      if (ci_number_el.val().length > 0)
        getRepairOrders('/get_repair_orders_by_order_number/','order_number='+ci_number_el.val(),false);
    }
  }

  function importFromAyax () {
    if (!$('#import_btn').attr('disabled'))
    {
      $('#import_btn').attr('disabled',true);
      $('#refresh_icon').css('display','block');
      $('#okay_icon').css('display','none');
      var chassis_number_el = $('#repair_order_car_chassis_number');
      if (chassis_number_el.val().length == 17)
        $.get('/import_data_from_ayax/'+chassis_number_el.val(),function(res){
          $('#import_btn').attr('disabled',false);
          $('#refresh_icon').css('display','none');
          $('#okay_icon').css('display','block');
          location = '/repair_orders/?chassis_number='+chassis_number_el.val();
        }).fail(function(res) {
          console.log(res);
          $('#refresh_icon').css('display','none');
          $('#fail_icon').css('display','block');
        })
    }
  }
</script>

app/views/repair_orders/new.html.erb
<div class="row">
  <div class="col-lg-6">
  <%= link_to t('back'), repair_orders_path, class: 'btn btn-primary btn-back new__back-button' %>
  <h1 class="new__title"><%= t('new_repair_order') %></h1>
  </div>
</div>

<%= render 'form', repair_order: @repair_order %>

app/views/repair_orders/show.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>


<div class="col-lg-4">

  <h1><%= t('order_information_number') %> <%= @repair_order.order_number %></h1>
  <%= link_to t(:edit), edit_repair_order_path(@repair_order), class:"btn btn-primary" %>
  <%= link_to t(:back), repair_orders_path, class:"btn btn-primary" %>

  <table class="table table-striped table-hover ">
    <tbody>
      <tr>
        <td>
          <strong><%= t('order_number') %></strong>
        </td>
        <td>
          <%= @repair_order.order_number %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('car') %></strong>
        </td>
        <td>
          <a href="<%= car_path(@repair_order.car) %>"><%= @repair_order.car.name %></a>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('mechanic') %></strong>
        </td>
        <td>
          <%= @repair_order.mechanic.name %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('type') %></strong>
        </td>
        <td>
          <%= t(@repair_order.order_type.downcase) %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('description') %></strong>
        </td>
        <td>
          <%= @repair_order.description %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('note') %></strong>
        </td>
        <td>
          <%= @repair_order.note %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('in_ayax') %></strong>
        </td>
        <td>
          <%= @repair_order.ayax? ? t('yes') : t('no') %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('kilometers') %></strong>
        </td>
        <td>
          <%= @repair_order.kilometers %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('repair_date') %></strong>
        </td>
        <td>
          <%= @repair_order.repair_date %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('compliance_date') %></strong>
        </td>
        <td>
          <%= @repair_order.compliance_date %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('claim_number') %></strong>
        </td>
        <td>
          <%= @repair_order.claim_number %>
        </td>
        <td colspan="1"></td>
      </tr>
      <tr>
        <td>
          <strong><%= t('operation_number') %></strong>
        </td>
        <td>
          <%= @repair_order.operation_number %>
        </td>
        <td colspan="1"></td>
      </tr>
    </tbody>
  </table>
</div>