config/routes.rb
Rails.application.routes.draw do
  resources :mechanics
  resources :countries
  resources :states
  resources :cities
  resources :repair_orders
  resources :manuals
  resources :technical_reports
  resources :cars
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'repair_orders#index'

  get '/chassis_numbers' => 'cars#get_chassis_numbers'
  get '/repair_order_numbers' => 'repair_orders#get_numbers'
  get '/get_car_by_chassis_number/:chassis_number' => 'cars#get_by_chassis_number'
  get '/get_car_by_client_identification/:identification' => 'cars#get_by_client_identification'
  get '/import_data_from_ayax/:chassis_number'=>'repair_orders#import_from_ayax'
  #get '/repair_orders/' => 'repair_orders#index'
  post '/get_repair_orders_by_chassis_number' => 'repair_orders#get_by_chassis_number'
  post '/get_repair_orders_by_order_number' => 'repair_orders#get_by_order_number'

  post '/clients/get_by_name' => 'clients#get_by_name'
  post '/cars/get_by_identification' => 'cars#get_by_identification'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_one :manual
  has_many :technical_reports
  has_many :repair_orders

  alias_attribute :name,:model

  def client?
    self.client != nil
  end

  def self.get_by_chassis_number chassis_number
    @car = self.where("chassis_number = ?", "#{chassis_number}")
    @car.first
  end

  def self.get_by_identification identification
    self.where("chassis_number ilike ? or engine_number ilike ? or plate ilike ?",
     "%#{identification}%", "%#{identification}%", "%#{identification}%").order('updated_at DESC').limit(40)
  end

  def name
    "#{self.brand} #{self.model} (Chasis: #{self.chassis_number.upcase})" #, Cliente: #{self.client.name})
  end
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :clients

  def self.get_by_name name
    @city = self.where("name ilike ?", "%#{name}%")
    @city.first
  end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :city
  has_many :cars

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def self.get_by_identification identification
    @client = self.where("identification = ?", "#{identification}")
    @client.first
  end

  def self.get_by_name name
    self.where("first_name ilike ? or last_name ilike ?", "%#{name}%", "%#{name}%").order('updated_at DESC').limit(40)
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/manual.rb
class Manual < ApplicationRecord
  belongs_to :car

  def name
    'Manual'
  end
end

app/models/mechanic.rb
class Mechanic < ApplicationRecord
  belongs_to :city
  has_many :repair_orders

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def self.get_by_name name
    @mechanic = self.where("first_name ilike ? or last_name ilike ?", "%#{name}%", "%#{name}%")
    @mechanic.first
  end
end

app/models/repair_order.rb
class RepairOrder < ApplicationRecord
  belongs_to :car
  belongs_to :mechanic

  def car?
    self.car != nil
  end

  def car_chassis_number
    car.try(:name)
  end

  def car_chassis_number=(name)
    self.car = Car.find_by(chassis_number: name) if name.present?
  end

  def ci_number
    self.car.try(:name)
  end

  def ci_number=(name)
    self.car.client.ci = Car.find_by(ci_number: name) if name.present?
  end

  def car_select
    "car_select"
  end

  def self.get_by_order_number order_number
    repair_order = self.where("order_number = ?", "#{order_number}")
    repair_order.first
  end

  def self.get_many_by_order_number order_number
    repair_orders = self.where("CAST(order_number AS TEXT) ilike ?", "%#{order_number}%").order('order_number DESC').limit(40)
    repair_orders = [] unless !repair_orders.nil?
    repair_orders
  end

  def self.get_by_chassis_number chassis_number
    car = Car.get_by_chassis_number chassis_number

    repair_orders = car.repair_orders unless car.nil?
    repair_orders = [] unless !repair_orders.nil?
    repair_orders
  end

  def self.get_by_identification identification
    client = Client.get_by_identification identification
    repair_orders = nil
    unless client.nil? then
      # if client.cars.empty? then
      #   repair_orders = []
      # else
        client.cars.each do |car|
          if repair_orders.nil? then
            repair_orders = car.repair_orders
          else
            repair_orders += car.repair_orders
          end
        end
      # end
    end

    repair_orders = repair_orders.nil? ? [] : repair_orders
    repair_orders
  end

end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/technical_report.rb
class TechnicalReport < ApplicationRecord
  belongs_to :car
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_clients, only: [:new, :edit]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.paginate(:page => params[:page], :per_page => 10).order('id DESC')
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /get_car_by_chassis_number/1
  def get_by_chassis_number
    @car = Car.order('chassis_number DESC').where("chassis_number = ?", "#{params[:chassis_number]}").limit(10)
    render json: @car
  end

  # GET /get_car_by_client_identification/1
  def get_by_client_identification
    @client = Client.where("identification = ?", "#{params[:identification]}").first

    @car = 'not found'
    @car = @client.cars unless @client.nil?

    render json: @car
  end

  # GET /cars/get_by_identification
  def get_by_identification
    @cars = Car.get_by_identification params[:car_identification]
    render :layout => false
  end

  # GET /get_chassis_numbers/1
  def get_chassis_numbers
    @chassis_numbers = Car.order('updated_at DESC').where("chassis_number ilike ?", "%#{params[:term]}%").limit(10)
    render json: @chassis_numbers.map(&:chassis_number)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def set_clients
      @clients = Client.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:client_id, :brand, :model, :chassis_number, :engine_number, :plate, :kilometers, :sell_date, :car_identification)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/mechanics_helper.rb
module MechanicsHelper
end

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper
  def campaign_path campaign
    repair_order_path campaign
  end
  def repair_path repair
    repair_order_path repair
  end
  def service_path service
    repair_order_path service
  end
  def warranty_path warranty
    repair_order_path warranty
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guillermo Fielitz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Material Design fonts -->
<!--     <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/assets/favicon.png">
  </head>

  <body>
        <div class="navbar <%= @side_color %> noMargin">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-warning-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="padding-top: 12px; padding-left: 10px;"><img src="/assets/logo.png" style="width: 170px;"></a>
                <div class="app_version hidden">v0.1.0</div>
            </div>
            <div class="navbar-collapse collapse navbar-warning-collapse">
                <ul class="nav navbar-nav">
                  <li id="repair_orders">
                    <%= link_to t('repair_orders'), repair_orders_path %>
                  </li>
                  <li id="clients">
                    <%= link_to t('clients'), clients_path %>
                  </li>
                  <li id="cars">
                    <%= link_to t('cars'), cars_path %>
                  </li>
                  <li id="manuals">
                    <%= link_to t('manuals'), manuals_path %>
                  </li>
                  <li id="mechanics">
                    <%= link_to t('mechanics'), mechanics_path %>
                  </li>
                  <li id="technical_reports">
                    <%= link_to t('technical_reports'), technical_reports_path %>
                  </li>
                  <li id="cities">
                    <%= link_to t('cities'), cities_path %>
                  </li>
                  <li id="states">
                    <%= link_to t('states'), states_path %>
                  </li>
                  <li id="countries">
                    <%= link_to t('countries'), countries_path %>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <% #if current_user != nil %>
                        <h3 class="user_name"><%= t('hello') %></h3>
                    <% #end %>

                    </li>
    <!--                 <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                            <% if I18n.locale == :es %>
                            ES
                            <% else %>
                            EN
                            <% end %>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <% if I18n.locale == :es %>
                                <li><a href="javascript:selectLanguage('en')">EN</a></li>
                            <% else %>
                                <li><a href="javascript:selectLanguage('es')">ES</a></li>
                            <% end %>
                        </ul>
                    </li> -->
                </ul>
            </div>
        </div>
    <%= yield %>
    <script>
        $(function() {
            $.material.init();
            $('#<%= controller_name %>').addClass("active")
        });
    </script>
  </body>
</html>